name: Pentaho Merge Compliance
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      - "+([0-9])*(.+([0-9]))"
    paths-ignore:
      - .github/**
jobs:
  run-merge-compliance:
    name: Run Merge Compliance Checks
    uses: pentaho/actions-common/.github/workflows/merge_compliance.yml@compliance
    with:
      scpId: 3ef4b1f1-778b-4204-94ae-5c7e360f13ab
    secrets: inherit

